import { User } from '@/types/users'

export const mockUsers: (User & { password: string })[] = [
  {
    id: '1',
    email: 'admin@inventory.com',
    firstName: 'John',
    lastName: 'Doe',
    password: 'admin123', // In real app, never store plain passwords!
    role: 'admin',
    department: 'Management',
    phone: '+1 (555) 123-4567',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    isActive: true,
    lastLogin: new Date('2024-01-20T10:30:00'),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    email: 'manager@inventory.com',
    firstName: 'Jane',
    lastName: 'Smith',
    password: 'manager123',
    role: 'manager',
    department: 'Operations',
    phone: '+1 (555) 234-5678',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    isActive: true,
    lastLogin: new Date('2024-01-19T14:20:00'),
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '3',
    email: 'staff@inventory.com',
    firstName: 'Bob',
    lastName: 'Johnson',
    password: 'staff123',
    role: 'staff',
    department: 'Warehouse',
    phone: '+1 (555) 345-6789',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    isActive: true,
    lastLogin: new Date('2024-01-18T09:15:00'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '4',
    email: 'viewer@inventory.com',
    firstName: 'Alice',
    lastName: 'Williams',
    password: 'viewer123',
    role: 'viewer',
    department: 'Finance',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    isActive: true,
    lastLogin: new Date('2024-01-17T16:45:00'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '5',
    email: 'susan@inventory.com',
    firstName: 'Susan',
    lastName: 'Taylor',
    password: 'susan123',
    role: 'staff',
    department: 'Procurement',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Susan',
    isActive: false, // Inactive user
    lastLogin: new Date('2024-01-10T11:00:00'),
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-10'),
  },
]